### PR TITLE
DB-838, DB-843: Handle Intersection character in perl proforma parser

### PR DESCRIPTION
**Pull request by gildossantos**
I used this as a reference for how to handle the intersection character.
https://www.compart.com/en/unicode/U+2229

I suggest that curators use `&cap;` when submitting proforma; this will be converted to `intersection` for plain text, and the actual `∩` character where we display the full unicode character set.

### CODE REVIEW

**Comment by gm119** [comment]
I think that this looks good. (I got a bit hung up on whether the recon change could potentially cause a `&cap;` where we wouldn't want it e.g. if the word intersection was used in a free text sentence ), but realised that its only being used to convert symbols to add synonyms so all good

**Comment by gildossantos** [comment]
Yeah, the `recon` function is a bit worrisome. If we're really worried, we could use `INTERSECTION` (ALL CAPS) instead of `intersection`, since the former is less likely to naturally occur in a sentence?

**Comment by gm119** [comment]
yeah, maybe all caps would be better (a bit like like the BEFORE/AFTER in decon) ?
The only place I could find `recon` being used was in `write_feature_name_change_synonyms`, which is itself used in sub `feature_name_change_action` so I'm thinking its only symbols and not actually called in a sentence, but maybe INTERSECTION just in case wouldn't hurt ?

**Comment by gildossantos** [comment]
I've run this modified code on many test proforma with real data and to the best of my knowledge, things are working as expected. The code now supports curation of expression for "split system combination" entities, as well as renaming/merging of existing and creation of new "split system combination" entities. Existing expression curation functionality is not affected in various tests. There are checks to ensure that expression curation to XR/XP, RA/PA and split system combination features stays separate. I think it's ready for production.

**Comment by ianlongden** [comment]
Where does the var $type get set to 'split system combination'?
I can see lots of tests for if $type = 'split system combination' in the code but nowhere where it is set. Not finished my coffee yet so may be that.

**Comment by gildossantos** [comment]
> Where does the var $type get set to 'split system combination'? I can see lots of tests for if $type = 'split system combination' in the code but nowhere where it is set. Not finished my coffee yet so may be that.

@ianlongden - `$type` gets set on lines 825 and 826 of the new code. I had to modify that code to allow for "FBcv:" prefix in the ID given after the CV term name (previously was limited to SO terms).

**Review by ianlongden — APPROVED** [review]
Added official tests for this and it seems to do what I expected, so happy to pass it.

**Comment by gildossantos** [comment]
Thanks @ianlongden. No rush on this so I'll wait for @gm119 to have a close look at this (while updating Peeves), just in case she spots something.

**Review by gm119 — APPROVED** [review]
This all looks fine for merging into production (NB, change to curation practice will need to wait until I've done my bit for Peeves and support scripts, but we may as well merge this in now as its finished)

**Pull request merged**
